custom collections
andriidome/HillelHomeworkC pull request #3
Opened 2024-07-07 16:41 UTC by andriidome

2024-07-07 17:39 UTC, Delvin09 requested changes
Все ок, только форматирование плывет иногда. Делай периодически Ctrl+K+D (для VS) + поторопился с дженериками, они пойдут в след. дз (можешь не переделывать, просто доработай что не сделал).
Ну и хорошо бы сделать связные списки, там самая мякотка по наследованию, и полиморфизму.

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomLibrary/CustomTree.cs
> +                key = value;
ключ должен быть ридонли

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomLibrary/CustomTree.cs
> +		private CustomNode<T>? left;
можно переделать в авто свойства свойства

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomLibrary/CustomTree.cs
> +	public class CustomNode<T>
поторопился, дженерики будут на след домашке

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomLibrary/CustomList.cs
> +                return usedCapacity;
тоже можно авто свойство с приватным сеттером

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomLibrary/CustomList.cs
> +        private int capacity;
Капасити == underlyingArray.Length

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomLibrary/CustomList.cs
> +		{
почему "едет" форматирование? или это только в гитхабе?

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomLibrary/CustomList.cs
> +            for (int i = 0; i < usedCapacity; i++)
IndexOf() >= 0

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomLibrary/CustomList.cs
> +        public T? this[int index] {
групперуй в классе, сначала константы, потом статику, потом поля, свойства, конструктор и методы

2024-07-07 17:39 UTC, Delvin09 commented on CustomCollections/CustomCollections.sln
> +﻿
При создании проекта не выставляй галочку 
![image](https://github.com/andriidome/HillelHomeworkC/assets/29715723/542eb869-e5ba-4335-aca3-4f5058e65adb)

2024-07-11 13:40 UTC, andriidome commented on CustomCollections/CustomLibrary/CustomList.cs
> +		{
это гитхаб
<img width="423" alt="Screenshot 2024-07-11 at 16 39 45" src="https://github.com/andriidome/HillelHomeworkC/assets/173537734/025b151a-2f82-4c15-8e02-23edb75c2138">

2024-08-04 12:26 UTC, merged